### ISSUE TITLE
Catalog of Items definiert

### ISSUE THREAD

**Issue by DannyAmmon** [medizininformatik-initiative/INTERPOLAR#1]

**Comment by neumdan** [comment]
COI with the FHIR-resources of interest lies and the description why the items are needed lies [here](https://tmfev.sharepoint.com/:x:/r/sites/tmf/mi-i/Modul3Projekte/INTERPOLAR/3_Taskforces/TF%20Datenflussmodell/[interpolar_coi.xlsx](https://tmfev.sharepoint.com/:x:/r/sites/tmf/mi-i/Modul3Projekte/INTERPOLAR/3_Taskforces/TF%20Datenflussmodell/interpolar_coi.xlsx?d=wce599750a7924233bf21a7da7f7a3ede&csf=1&web=1&e=utoWho)?d=wce599750a7924233bf21a7da7f7a3ede&csf=1&web=1&e=utoWho)
