### ISSUE TITLE
Risikofaktor definiert

### ISSUE THREAD

**Issue by SebStaeubert** [medizininformatik-initiative/INTERPOLAR#11]

**Comment by wahram** [comment]
Update 12/23: Trigger für INTERPOLAR-1 stehen in Table unter folgender Tabelle fest: https://tmfev.sharepoint.com/:w:/r/sites/tmf/mi-i/_layouts/15/Doc.aspx?sourcedoc=%7BA658B5D7-A5F1-4EAC-997F-2A00699D14BC%7D&file=Interpolar%20Risikoscoring%20Erl%C3%A4uterung%20der%20Ergebnisse%20sent%2017-07-2023.docx&action=default&mobileredirect=true
