### ISSUE TITLE
Redcap API Token und URL in db2frontend_config.toml

### ISSUE THREAD

**Issue by SebStaeubert** [medizininformatik-initiative/INTERPOLAR#120]
aktuell fehlen diese beiden Variablen

**Comment by mayadogh** [comment]
was genau meinst du? die sind in der toml-Datei gewesen, wir können die aber nicht vorgeben. URL & API-Token sind Instanz-spezifisch und müssen Vorort definiert werden...

**Comment by SebStaeubert** [comment]
Ist mit #1b9bac07 von @Flow191 gelöst.
