### ISSUE TITLE
E-Mailverteiler erstellen

### ISSUE THREAD

**Issue by Flow191** [medizininformatik-initiative/INTERPOLAR#153]
Um den Kontakt mit den DIZ-Mitarbeiter zu gewährleisten sollten wir einen Mail-Verteiler erstellen und alle IT-Mitglieder dort hinterlegen. Die Mail-Adresse sollte dann unter einen Punkt Ansprechpartner hier im Git angegeben werden.

**Comment by SebStaeubert** [comment]
Woher kommt die Anforderung?
Es gibt den IP-DIZ Verteiler - ist der nicht passend?
Sollte es einen IP-DIZ-IT Verteiler geben? Wird das nicht zu kleinteilig?
Vorschlag: Es gibt noch die IP-DIZ Tabelle im SharePoint - dort könnten wir die technischen Ansprechpartner hinterlegen.

**Comment by Flow191** [comment]
Wir sollten hier jetzt das neue Git Feature "Discussions" verwenden, wie bereits besprochen.
