### ISSUE TITLE
pgadmin: Konfiguration aus den Umgebungsvariablen (docker-compose, .env) erzeugen

### ISSUE THREAD

**Issue by SebStaeubert** [medizininformatik-initiative/INTERPOLAR#155]
... damit die DB-Verbindung bereits angelegt ist und dieser aktuell manuelle Schritt entfällt.

Update: Ist vermutlich nicht möglich. In der Doku (install.md) beschreiben bzw. ggf. Beschreibung anpassen.

**Comment by SchmitzDan** [comment]
Könnte folgendermaßen funktionieren:
- Server Config als json erstellen (oder aus funktionierender Instanz über Tools>Import/Export Servers exportieren)
- json in den Container mounten nach /pgadmin4/servers.json oder anderen Pfad und diesen dann in ENV PGADMIN_SERVER_JSON_FILE konfigurieren

CAVE: Wenn irgendwo ein HTTP_PROXY oder HTTPS_PROXY definiert ist muss der Containername der DB in NO_PROXY angegeben werden, sonst funktioniert die Kommunikation der Container untereinander nicht
