### ISSUE TITLE
Redcap deploy: Variante 2 - Anbindung einer bestehenden Redcap-Instanz

### ISSUE THREAD

**Issue by SebStaeubert** [medizininformatik-initiative/INTERPOLAR#161]
Siehe Variante 2 in #76

ToDo:

- [ ] Doku erstellen
  - Voraussetzungen beschreiben
  - Netzwerkzugriffe beschrieben
  - Redcap/Projekt Setup mit API-Token, Import/Export Scripte, etc.

**Comment by mayadogh** [comment]
duplicate von task 2 von #76
