### ISSUE TITLE
Kopie des INTERPOLAR-Dev Projekts in REDCap mit neuen Nützern

### ISSUE THREAD

**Issue by mayadogh** [medizininformatik-initiative/INTERPOLAR#167]
MLö möchte, dass er, die anderen PIs (also: Renke Maas & Andre Scherag) und Daniel Neumann auch in REDCap sich anschauen was für Möglichkeiten für Reporting gibt. Daher, hätten wir gerne eine komplette Kopie des INTERPOLAR-Dev Projekts mit allen Daten in einem neuen Projekt, wo ich die selbe Rolle als vorher habe und die Herren die Rolle vom Apotheker für IP.
Gerne kann das INTERPOLAR-Dev2 ersetzen wenn das sinnvoller wäre.

**Comment by SebStaeubert** [comment]
@mayadogh es gibt bereits [INTERPOLAR-Dev2](https://www.health-atlas.de/redcap-test/redcap_v14.3.1/index.php?pid=46) - kann dieses dafür verwendet werden? Ich würde es dann umbenennen in INTERPOLAR-Test - was meinst Du?

**Comment by mayadogh** [comment]
Ja, gerne Dev2 verwenden. Danke.

**Comment by SebStaeubert** [comment]
- [x] Bisheriges Projekt INTERPOLAR-Dev2 gelöscht
- [x] Projekt INTERPOLAR-DEV als ODM, sowie Nutzer, Rollen und Nutzer-Rollen-Zuordnung exportiert
- [x] Projekt [INTERPOLAR-Test](https://www.health-atlas.de/redcap-test/redcap_v14.3.1/index.php?pid=49) mit den Daten (ODM+Nutzer/Rollen) von INTERPOLAR-DEV angelegt
