### ISSUE TITLE
Erstellung und Speicherung von Performance Dateien

### ISSUE THREAD

**Issue by Flow191** [medizininformatik-initiative/INTERPOLAR#169]

**Comment by Flow191** [comment]
Siehe Funktion save_performance() in lib_dir.

**Comment by SebStaeubert** [comment]
@Flow191 Ist das bis 23.05.2024 umzusetzen? Ist es für 1-a relevant? Wenn nein -> [Release 0.3.0](https://github.com/medizininformatik-initiative/INTERPOLAR/milestone/10) geschoben werden?
