### ISSUE TITLE
technische ID vs. PatID zum Filtern der Patienten

### ISSUE THREAD

**Issue by KoesterH** [medizininformatik-initiative/INTERPOLAR#187]
Hallo, in Erlangen haben wir das Filtern über die Patienten-Liste source_PIDs.txt ausprobiert. Auf Euren Testdaten klappt es wunderbar. Mit unseren realen Daten leider nicht. Gebe ich in der Liste die Pat-IDs an, werden keine Patienten, keine Encounter und keine sonstigen Ressourcen gefunden (nur Locations). Frage ich unseren FHIR-Server direkt mit ../Patient?identifier=Patidxyz sind die Ressourcen aber da. Trage ich in die source_PIDs.txt die technische FHIR-ID der entsprechenden Patienten-Ressourcen ein, werden zwar keine Patienten aber die anderen Ressourcen gefunden.
Kann es sein, dass Eure Abfragen davon ausgehen, dass die technische-ID = PatID ist?

**Comment by Flow191** [comment]
Hallo Helene, wir haben das Logging verbessert. Die FHIR-Requests werden jetzt in der log-Datei im OutputLocal, als auch in dem Ordner "bundles" geloggt, wenn in der kds2db_config.toml das verbose-level auf 10 gesetzt wird. Wir haben die Änderungen in einen tag vom release gepackt (v0.1.1). Hierfür bitte den folgenden tag auschecken: "git checkout tags/v0.1.1". Dann nochmal Modul kds2db starten und dann kannst du die Requests sehen und mit den von dir erwarteten Requests vergleichen. Vielleicht fällt dir dann der Unterschied in den Anfragen auf, damit wir den Fehler ausfindig machen können.

**Comment by KoesterH** [comment]
Danke, ich habe es eben ausprobiert: die Ordner OutputLocal und OutputGlobal sind/bleiben leer und einen Ordner bundles hab ich gar nicht? 
Im Konsolen-log sehe ich sowas wie "https://mii-agiop-3p.life.uni-leipzig.de/blaze/Observation?_summary=count&_count=1&__t=29035" (für den Lauf auf dem Testserver). Das ist aber nur wenig hilfreich, da nicht die eigentliche Abfrage.

**Comment by Flow191** [comment]
Hm dann hat das nicht geklappt mit dem auschecken des korrekten branches. Du müsstest diesen branch/tag hier auschecken: https://github.com/medizininformatik-initiative/INTERPOLAR/tree/v0.1.1
Mit "git describe --tags" solltest du sehen, ob du auf dem richtigen tag bist.

**Comment by KoesterH** [comment]
Ich bin/war auf auf dem richtigen Tag. Die Dateien sehen auch richtig abgeändert aus. Als Versuch habe ich hab alle Container und Images gelöscht und wollte sie neu bauen. Aber es kommt der Fehler: 
 > [ 7/16] RUN R CMD INSTALL --preclean --no-multiarch --with-keep.source R-etlutils/etlutils:
#0 1.168 * installing to library ‘/usr/local/lib/R/site-library’
#0 1.184 ERROR: dependency ‘ICD10gm’ is not available for package ‘etlutils’
#0 1.185 * removing ‘/usr/local/lib/R/site-library/etlutils’
------
failed to solve: process "/bin/sh -c R CMD INSTALL --preclean --no-multiarch --with-keep.source R-etlutils/etlutils"

**Comment by KoesterH** [comment]
Eure Abfragen sind so gebaut, dass sie bei uns mit der Fhir_id anstatt der PatID funktionieren sollten. In Euren Test-Patientenresourcen sind die beiden IDs identisch, bei uns nicht. 

Also bei Euch sieht es so aus: 
"resourceType": "Patient",
 "id": "Polar-WP1.1-XYZ",
 "identifier": [
                    { ....
                        "system": "...",
                        "value": "Polar-WP1.1-XYZ"
                    }
  ],
     
unsere FHIR-Patienten sehen hingegen so aus:
 "resourceType": "Patient",
 "id": "fhir_id",
  "identifier": [
              { ...
               "system": "...",
                "value": "PatID" (pseudonymisiert)
                 }
          ],
Warum allerdings auf unserem FHIR-Server auch mit der Fhir_id es im Endeffekt nicht geklappt hat, ist mir nicht klar geworden (da hatte das Skript zwar die weiteren Ressourcen gefunden aber keine Patienten und auch nichts in die Datenbank geschrieben).

Viel mehr kann ich gerade auch nicht ausprobieren, weil das Retrieval aus dem release branch nicht  komplett durchläuft (es Endet mit einem  Error in if (!is.na(value) && nchar(value) > max_length) { : \n  missing value where TRUE/FALSE needed\n ) und egal wie am Ende nichts in der Datenbank landet. Auch ist es mir nicht gelungen unseren FHIR-Server dort erfolgreich zu verbinden (ich habe Endpoint/User/Passwort genauso eingetragen wie in der ursprünglichen Version aber es hat nicht funktioniert). Außerdem nimmt die neue Version Änderungen in der source_PIDs.txt nur an, wenn man das r-env Image löscht und neu erstellt. 

Wie komme ich zurück auf die "ursprüngliche" Version? Also die nach Eurem ersten Release im Mai. Ich weiß leider nicht mehr welche Version das war.

**Comment by Flow191** [comment]
Wir sind gerade an einen Entwicklungsstand, wo sich die Datenbank von dem kds2db Modul etwas unterscheidet. Die von der Datenbank erwarteten Datenstruktur ist anders als die FHIR-Daten die wir dort rein schreiben möchten. Wir sind gerade dabei daran zu arbeiten.
Die Version des ersten Release ist diese hier: https://github.com/medizininformatik-initiative/INTERPOLAR/tree/v0.1.0-alpha

**Comment by Flow191** [comment]
Hallo Helene, besteht das von dir oben geschilderte Problem weiterhin auf den aktuellen Release `v0.2.2`, oder kann dieses Issue geschlossen werden?

**Comment by KoesterH** [comment]
Ihr könnt das issue schließen.
ich hab es zwar immer noch nicht hinbekommen mit der liste erfolgreich zu filtern, aber es mit der neuen Version auch nur kurz ausprobiert. Ich werde das nochmal intensiver testen und dann ggf. ein neues Issue erstellen.
Ein Punkt fällt mir da gerade ein: wenn man was an der Liste (der source_PIDs.txt) ändert, muss man das Interpolar-R-env Image löschen und es neu bauen, damit die Änderungen übernommen werden. Für einen produktiv-Betrieb ist das eher unpraktisch (aber auch das ist ja ein anderes Thema).

**Comment by Flow191** [comment]
Alles klar, danke für den Hinweis, werden wir noch testen.
