### ISSUE TITLE
REDCap-Dev anderswo deployen

### ISSUE THREAD

**Issue by mayadogh** [medizininformatik-initiative/INTERPOLAR#203]
Hi Seb,

kannst du bitte den jetztigen Stand des REDCap-Dev Projekts auf folgende Instanzen / Projekte übertragen? (Insgesamt, mit Daten und allem):

- [x] 1. REDCap-Test Projekt auf HealthAtlas
- [x] 2. REDCap-Dev Projekt auf LIFE-VM

Danke!

**Comment by SebStaeubert** [comment]
zu 1.
@mayadogh Kann INTERPOLAR-Test überschrieben werden?

zu 2.
Das Setup dort ist "dynamisch". Alle Entwickler können bei Bedarf dort experimentieren. Ich mach den Export/Import jetzt noch einmal. Zukünftig kann das jeder im IP-IT Team (ggf. in einem eigenen Setup) selbst machen.

**Comment by SebStaeubert** [comment]
> zu 1. @mayadogh Kann INTERPOLAR-Test überschrieben werden? Ja bitte... Es gab noch neues gestern, es wäre gut den Stand von heute vom DEV zu nehmen.

- [x] Erledigt: [INTERPOLAR-Test](https://www.health-atlas.de/redcap-test/redcap_v14.3.11/UserRights/index.php?pid=51)


> zu 2. Das Setup dort ist "dynamisch". Alle Entwickler können bei Bedarf dort experimentieren. Ich mach den Export/Import jetzt noch einmal. Zukünftig kann das jeder im IP-IT Team (ggf. in einem eigenen Setup) selbst machen. Ich bin aber nicht Admin dort, kann kein Projekt anlegen. UND weiß auch nicht wie das geht. Vorschlag, wenn Marcel im Team ist, soll er Admin-Rechte bekommen.

Es gibt auf interpolar-dev keine Einschränkungen. Jeder der Zugriff hat, ist Admin und kann Projekte importieren.

Ticket bitte schließen, wenn alles passt. THX, Seb.
