### ISSUE TITLE
Benutzerhandbuch Frontend (REDCap)

### ISSUE THREAD

**Issue by SebStaeubert** [medizininformatik-initiative/INTERPOLAR#243]
- [ ] Ablauf beschreiben (Einloggen, Report aufrufen, usw.)
- [ ] Benutzung der INTERPOLAR Formulare / Reports beschreiben
   - [ ] Benutzen der Report <a> beschreiben
   - [ ] Benutzen der Report <b> beschreiben
   - [ ] usw. <hier weitere Formular, Reports ergänzen>

**Comment by mayadogh** [comment]
1 erste Version ist von Joachim Köck geschrieben worden, die aber angepasst werden muss auf eine generische REDCap-Installation & für automatische Imports von Fall.

[20240611 Kurzanleitung-1.docx](https://github.com/user-attachments/files/15871015/20240611.Kurzanleitung-1.docx)
[20240611 Anleitung Cockpit.pdf](https://github.com/user-attachments/files/15871016/20240611.Anleitung.Cockpit.pdf)

**Comment by mayadogh** [comment]
Achims Dokument ist fast final, @MarcelvonBorzestowski bitte hierzufügen wenn fertig und Issue closen. Ich nehme mich aus den Issues langsam raus.
