### ISSUE TITLE
REDCap Projekt zur Apothekertestung vorbereiten

### ISSUE THREAD

**Issue by mayadogh** [medizininformatik-initiative/INTERPOLAR#268]
Bitte um folgendes:

- [x] REDCap Projekt INTERPOLAR-Test auf HealthAtlas ersetzten / erneuern (.zip Datei in diesem Issue enthält die xml-Datei dazu)
- [x] Neue Zugänge für mehr Apotheker einrichten (die finale Liste mit Name / Email-adressen kommt noch)

[INTERPOLARDev_2024-06-11_0734.REDCap.zip](https://github.com/user-attachments/files/15784000/INTERPOLARDev_2024-06-11_0734.REDCap.zip)

**Comment by mayadogh** [comment]
Variante A bitte - ich habe sicherheitshalbe alles nochmal exportiert und hoffe, dass auch die Nutzer dabei sind. Ich habe nichts abgewählt.
Die 2. Datei (Excel) ist die Liste der Nutzer, inkl. neue.

[INTERPOLARDev_2024-06-11_1126.REDCap.zip](https://github.com/user-attachments/files/15787055/INTERPOLARDev_2024-06-11_1126.REDCap.zip)
[Testpersonen.xlsx](https://github.com/user-attachments/files/15787062/Testpersonen.xlsx)

**Comment by mayadogh** [comment]
Noch besser diese Datei.
[INTERPOLARDev_2024-06-12_1121.REDCap.zip](https://github.com/user-attachments/files/15803875/INTERPOLARDev_2024-06-12_1121.REDCap.zip)
[INTERPOLARDev_2024-06-12_1121.REDCap.zip](https://github.com/user-attachments/files/15803875/INTERPOLARDev_2024-06-12_1121.REDCap.zip)

**Comment by SebStaeubert** [comment]
REDCap Zugänge angelegt und der Test-Nutzer Rolle zugewiesen.
@mayadogh Soll das Projekt noch einmal von dev nach test kopiert werden? Oder sollen diese Nutzer in dev testen? Die Test-Rolle könnte noch angepasst werden, sodass nur ein lesender Zugriff möglich ist.

**Comment by mayadogh** [comment]
@SebStaeubert die Nutzer der Rolle IP-Test-Personon sollen nur in Test testen, die anderen Zugang zu beiden Dev & Test. Ich finde es eine Gute Idee wenn die test-Rolle nur lesenden Zugriff hätte. Danke!

**Comment by SebStaeubert** [comment]
@mayadogh Kannst Du die Anfrage bitte präzise stellen? In welchem redcap-Projekt soll welche Rolle welche Rechte bekommen?

**Comment by mayadogh** [comment]
Es scheint alles richtig zu sein und die Testungsrunde ist schon beendet. Ich schließe dieses Issue.
