### ISSUE TITLE
Skript zum Daten aus DB holen

### ISSUE THREAD

**Issue by SebStaeubert** [medizininformatik-initiative/INTERPOLAR#28]
- IC 
- In: INTERPOLAR-Clinical-DB 
- Out: Schöne Anzeige auf dem Monitor für den Apotheker 
- Verantw.: MYD

**Comment by SebStaeubert** [comment]
Kann dieses Ticket geschlossen werden?

**Comment by mayadogh** [comment]
Diese Konzept haben wir schon getestet, werde dieses Issue schließen.
