### ISSUE TITLE
Hinweis für NCC MERP Score im Frontend

### ISSUE THREAD

**Issue by mayadogh** [medizininformatik-initiative/INTERPOLAR#287]
Wenn das MRP ein Medikationasfehler ist, soll der Nutzer einen Hinweis bekommen, dass er diesen Scorewert eingeben soll.

- [ ] Die Zustimmung der IP-Apothekern liegt vor

**Comment by mayadogh** [comment]
@MarcelvonBorzestowski : ist dies gelöst?

**Comment by MarcelvonBorzestowski** [comment]
Ja.

**Comment by MarcelvonBorzestowski** [comment]
Ein Score, der den potentiellen Schaden (für Subgruppe) abbildet, soll in der nicht näher bestimmten Zukunft hinzugefügt werden. 
Issue kann an dieser Stelle erstmal geschlossen werden.
