### ISSUE TITLE
Skript zum Daten in REDCap schicken

### ISSUE THREAD

**Issue by SebStaeubert** [medizininformatik-initiative/INTERPOLAR#29]
- IC 
- In: INTERPOLAR-Clinical-DB 
- Out: Schöne Anzeige auf dem Monitor für den Apotheker 
- Verantw.: MYD

**Comment by SebStaeubert** [comment]
Ist das ein Ticket für Release 0.2.0? Falls ja, bitte Milestone "Release v0.2.0" zuweisen.

**Comment by mayadogh** [comment]
Das ist ein generelles Ticket, gab bevor wir ein Release hatten... Lass uns besprechen ob wir für REDCap bzw. Definition des Frontends eigene Milestones anlegen...
