### ISSUE TITLE
checkError: wrong arguments for subsetting an environment

### ISSUE THREAD

**Issue by ghost** [medizininformatik-initiative/INTERPOLAR#290]
Guten Tag,

nach einem komplett frischem Aufsetzen von Interpolar, erhalten wir beim Ausführen von Punkt 2 "DataProcessor ausführen" des Abschnitts [Verwendung](https://github.com/medizininformatik-initiative/INTERPOLAR/tree/main?tab=readme-ov-file#verwendung) folgende Fehlermeldung:

```
3: Error in stopOnError(err) : \n
Run Dataprocessor: ERROR
Error in checkError(err = err, expr_ok = { : 
  Error in .lib_logging_env[[log_filename]] : 
  wrong arguments for subsetting an environment
Calls: dataprocessor ... <Anonymous> -> run -> runProcessInternal -> checkError
In addition: Warning message:
In sink() : no sink to remove
Execution halted
```
Wissen Sie woran das liegt? Kann der checkError reproduziert werden?

Vielen Dank

**Comment by astruebi** [comment]
Erst einmal kann ich den Fehler nicht nachvollziehen. Tritt er immer wieder auf? 

Das Komische ist, dass derselbe Code auch im "cds2db" zum Einsatz kommt. Wenn es wirklich falsch wäre, dürfte es dort auch nicht gehen. Bei uns mit Testsetttings funktioniert das Logging in beiden Modulen.

Können Sie es bitte noch einmal ausprobieren und gerne auch einfach nochmal  (vorher und/oder nachher) "cds2db" laufen lassen. Das sollte problemlos funktionieren.

**Comment by medicreitzner** [comment]
Guten Tag,

wir haben nun das Projekt auf einer frischen VM neu aufgesetzt und erhalten wieder folgendes:
```
                                                msg     id   state  nsecs
                                             <char> <char>  <fctr> <char>
1:                                             init    0        OK      0
2:                                Run Dataprocessor    1   RUNNING   <NA>
3: Create Frontend Tables for Patient and Encounter    1.1 RUNNING   <NA>
                 start                 end  error
                <POSc>              <POSc> <char>
1: 2024-06-27 16:12:10 2024-06-27 16:12:10       
2: 2024-06-27 16:12:11                <NA>       
3: 2024-06-27 16:12:11                <NA>       
Create Frontend Tables for Patient and Encounter: ERROR
                                                msg     id   state  msecs
                                             <char> <char>  <fctr> <char>
1:                                             init    0        OK       
2:                                Run Dataprocessor    1   RUNNING       
3: Create Frontend Tables for Patient and Encounter    1.1   ERROR    514
    µsecs  nsecs               start                 end
   <char> <char>              <POSc>              <POSc>
1:             0 2024-06-27 16:12:10 2024-06-27 16:12:10
2:          <NA> 2024-06-27 16:12:11                <NA>
3:    976    740 2024-06-27 16:12:11 2024-06-27 16:12:11
                            error
                           <char>
1:                               
2:                               
3: Error in stopOnError(err) : \n
                                                msg     id   state  msecs
                                             <char> <char>  <fctr> <char>
1:                                             init    0        OK       
2:                                Run Dataprocessor    1   RUNNING       
3: Create Frontend Tables for Patient and Encounter    1.1   ERROR    514
    µsecs  nsecs               start                 end
   <char> <char>              <POSc>              <POSc>
1:             0 2024-06-27 16:12:10 2024-06-27 16:12:10
2:          <NA> 2024-06-27 16:12:11                <NA>
3:    976    740 2024-06-27 16:12:11 2024-06-27 16:12:11
                            error
                           <char>
1:                               
2:                               
3: Error in stopOnError(err) : \n
Run Dataprocessor: ERROR
Error in checkError(err = err, expr_ok = { : 
  Error in .lib_logging_env[[log_filename]] : 
  wrong arguments for subsetting an environment
Calls: dataprocessor ... <Anonymous> -> run -> runProcessInternal -> checkError
In addition: Warning message:
In sink() : no sink to remove
Execution halted
```

Es scheint schon beim "Create Frontend Tables for Patient and Encounter    1.1   ERROR    514" einen Fehler zu werfen.
Wir haben uns strikt an die Install.md Dokumentation gehalten und dann die Skripte laufen lassen. Bei Skript 2 bekommen wir obiges Log.

Haben Sie eine Idee, ob noch eine Konfiguration fehlt, die nicht erwähnt wurde?

Vielen Dank!

**Comment by astruebi** [comment]
@medicreitzner : Wir können eine solche Fehlerausgabe reproduzieren. Ausgangspunkt ist aber mit ziemlicher Sicherheit ein anderer Fehler, der davor im Log stehen müsste. Die obige Fehlerausgabe ist nicht vollständig. Kurz davor steht wahrscheinlich die Ausgabe des ursächlichen Fehlers. ABER: Das Logging in die Log-Datei funktioniert im Modul "dataprocessor" in dieser Version nicht richtig. In der Konsole sollte die Ausgabe aber vollständig sein. Wir sind gerade dabei, diesen Logging-Fehler zu beheben.

Zu einem solchen Fehler kommt es immer dann, wenn im Modul "dataprocessor" irgendwas nicht geklappt hat. Am wahrscheinlichsten sind folgende Ursachen: 
1. Keine Daten in der Datenbank, weil in Modul "cds2db" keine Daten vom Server eingespielt wurden. Das passiert, wenn aus dem FHIR-Server keine Daten vorhanden sind, die zum aktuellen Datum passen, die Stationsfilter in der ["cds2db-config_toml"](https://github.com/medizininformatik-initiative/INTERPOLAR/blob/main/R-cds2db/cds2db_config.toml) nicht richtig gesetzt wurden oder die alternative Textdatei mit den Patienten-IDs vom FHIR-Server nicht richtig befüllt wurde. Siehe [README](https://github.com/medizininformatik-initiative/INTERPOLAR/tree/main/R-cds2db#readme). Nach dem Lauf des Modul "cds2db" kann in der Datenbank geprüft werden, ob Daten vorhanden sind. Im Datenbankschema "db_log" muss etwas in der Tabelle "pids_per_ward" stehen, sonst passiert im Modul "dataprocessor" nichts.
2. Der Start des Modul "dataprocessor" erfolgte zu schnell nach dem Modul "cds2db", so dass noch keine Daten im Kern der DB  (Schema "db_log") liegen. Zu schnell heißt, weniger als 1 Minute nach dem Ende des Moduls "cds2db". Das lässt sich ausschließen, indem man das Modul "dataprocessor" erst nach mind. einer Minute Wartezeit nach dem Modul "cds2db" ausführt. Die 1 Minute ergibt sich aus den Datenbank-Cron-Jobs, die nur die neuen Daten in den Datenbank-Kern übernehmen und minütlich laufen. Der detaillierte Datenfluss ist hier beschrieben: [Dataflow](https://github.com/medizininformatik-initiative/INTERPOLAR/blob/main/Dataflow.md).
3. Irgendein anderer Fehler, der in der Log-Ausgabe stehen sollte.

**Comment by astruebi** [comment]
Wir haben gerade den Fix im release-Branch hinzugefügt. Das bedeutet, das Logging ist jetzt so verbessert, dass der ursächliche Fehler als letztes in der Log-Ausgabe steht und sowohl die Konsole als auch die Log-Datei wieder alle Log-Messages enthalten. Damit sollte ersichtlich sein, was das eigentliche Problem ist.

Um diesen Branch zu nutzen muss der release-Branch ausgecheckt werden (siehe [Anleitung Schritt 3](https://github.com/medizininformatik-initiative/INTERPOLAR/blob/main/Install.md)).
