### ISSUE TITLE
DB2Frontend - Fehlermeldung während der Ausführung wegen fehlenden redcap_repeat_instance und redcap_repeat_instrument

### ISSUE THREAD

**Issue by bejoe1** [medizininformatik-initiative/INTERPOLAR#308]
Wenn ich das DB2Frontend-Skript starte (_docker compose run --rm --no-deps r-env Rscript R-db2frontend/StartDB2Frontend.R_) bekomme ich folgende Fehlermeldung:
```
importRecords will change how it validates data in version 3.0.0.
We recommend preparing your data for import using castForImport .
importRecords will change how it validates data in version 3.0.0.
We recommend preparing your data for import using castForImport .
Error in redcapError(response, error_handling = "error") :
  400: ERROR: "21896","patient_id_fk","21896","This field ('patient_id_fk') exists on a Repeating Instrument named 'fall'. However, the fields 'redcap_repeat_instance' and/or 'redcap_repeat_instrument' for this row of data have no value, which are both required for importing data into a Repeating Instrument.  You are not allowed to import data for this field into a non-repeating instrument."
"21896","fall_typ_id","17528","This field ('fall_typ_id') exists on a Repeating Instrument named 'fall'. However, the fields 'redcap_repeat_instance' and/or 'redcap_repeat_instrument' for this row of data have no value, which are both required for importing data into a Repeating Instrument.  You are not allowed to import data for this field into a non-repeating instrument."
"21896","fall_fe_id","3","This field ('fall_fe_id') exists on a Repeating Instrument named 'fall'. However, the fields 'redcap_repeat_instance' and/or 'redcap_repeat_instrument' for this row of data have no value, which a
Calls: copyDB2Redcap ... importRecords.redcapApiConnection -> import_records_unbatched -> redcapError
Execution halted
```
Woran genau kann dieser Fehler liegen? Ist das Problem nicht vorhandene Felder in unseren Daten, oder etwas anderes?
Ich habe in der DB im Schema **db_log** in der Tabelle **fall_fe** geschaut und dort sind die Attribute **redcap_repeat_instance** und **redcap_repeat_instrument** tatsächlich leer, also ist vermutlich beim Befüllen etwas schiefgelaufen, oder?

Vielen Dank im Voraus für die Hilfe!

**Comment by mayadogh** [comment]
Hallo! 
es klingt nach fehlende Werte tatsächlich. Da 1 Patient mehrere Fälle haben kann, ist der Fall als ein repeating instrument mit instance Nummer nur einlesbar für REDCap. Ich werde ein paar Kollegen hierzufügen die helfen können.

**Comment by mayadogh** [comment]
@astruebi & @reuschem : wenn die Felder redcap_repeat_instance und redcap_repeat_instrument leer sind kann Fall nicht importiert werden. Wo soll @bejoe1 schauen, in den FHIR-Daten, dass alles in Ordnung ist?

**Comment by reuschem** [comment]
Hallo @bejoe1,
wir werden in einem der nächsten Releases den Dataprocessor entsprechend anpassen das bei mehreren Fällen zu einem Patienten diese für RedCap durchnummeriert werden. Zu sehen sind die derzeit noch leeren Felder im Schema db2frontend_out in der View v_fall die Spalten redcap_repeat_instrument und redcap_repeat_instance.

Vielen Dank für den Hinweis

**Comment by reuschem** [comment]
Genau so ist es, wir werden diesen Bug bearbeiten.

**Comment by Flow191** [comment]
Fixed in branch #341
