### ISSUE TITLE
Skript zum Daten in DB zu schicken

### ISSUE THREAD

**Issue by SebStaeubert** [medizininformatik-initiative/INTERPOLAR#31]
- UC/IC 
- In: Formulareinträge 
- Out: INTERPOLAR-Clinical-DB 
- Verantw.:  MYD

**Comment by SebStaeubert** [comment]
Ist das ein Ticket für Release 0.2.0? Falls ja, bitte Milestone "Release v0.2.0" zuweisen.

**Comment by mayadogh** [comment]
Das ist ein generelles Ticket, gab bevor wir ein Release hatten...
