### ISSUE TITLE
FHIR-ID in RedCap

### ISSUE THREAD

**Issue by KoesterH** [medizininformatik-initiative/INTERPOLAR#326]
bei uns wird in RedCap die FHIR-ID der Patienten angezeigt und nicht wie gewünscht der identifier (welcher der PatID entspricht)

Edit: zu den IDs siehe auch der IG zum Modul Person: https://www.medizininformatik-initiative.de/Kerndatensatz/Modul_Person_Version_2/MIIIGModulPerson-TechnischeImplementierung-FHIR-Profile-PatientInPatient.html

**Comment by Flow191** [comment]
See changes here #340
