### ISSUE TITLE
Aus den FHIR Daten den KIS-PID statt die FHIR-ID im Frontend anzeigen - im DP und DB hinzufügen

### ISSUE THREAD

**Issue by reuschem** [medizininformatik-initiative/INTERPOLAR#331]
Im Frontend soll statt der FHIR ID des Patienten die KIS - ID des Patienten zur Wiedererkennung gezeigt werden. Die FHIR ID sollte zum Datenvergleich erhalten bleiben.

**Comment by astruebi** [comment]
duplicate zu #326
