### ISSUE TITLE
Anpassen der Frontendtabellen nach Begutachtung und Aenderungswuensche der Apotheker

### ISSUE THREAD

**Issue by reuschem** [medizininformatik-initiative/INTERPOLAR#336]
Die Apotheker begutachten gerade eine erste Version des Frontend. Sich daraus ergebenden sowie bereits in kleinerer Runde erkannten  Anederungswuenschen sollen umgesetzt werden. (Liste noch erweitern)
- [x] MRP Doku - 5 statt 3 Medikamente
- [x] Verknüpfung der Instrumente untereinander

Siehe [Frontend_Table_Description.xlsx](https://github.com/medizininformatik-initiative/INTERPOLAR/blob/release/R-db2frontend/db2frontend/inst/extdata/Frontend_Table_Description.xlsx)

**Comment by mayadogh** [comment]
Die Wünsche / Entscheidungen sind hier dokumentiert:
[20240723_Cockpit_INTERPOLAR.pdf](https://github.com/user-attachments/files/16377082/20240723_Cockpit_INTERPOLAR.pdf)

**Comment by reuschem** [comment]
- die Überarbeitung der Dokumentation durch die Apotheker erfolgte iterativ weiter und fand in einem finalen Beschluss am 04.09.2024 eine Version 1 die final angenommen wurde
-  die Verknüpfung der Instrumente untereinander soll über das jeweilige Datum erfolgen (siehe auch Dokumentation des Front Ends für Apotheker)
- Alle Änderungswünsche der Apotheker zum gegenwärtigen Zeitpunkt wurden im Frontend bzw. der Datenbankstruktur berücksichtigt und umgesetzt (Release 2.4)
- Nach der Plenumssitzung vom 18./19.9. und der Anpassung des Studienkonzeptes - ist damit zu rechnen das die Dokumentation angepasst bzw. erweitert wird - sobald dies abzusehen ist - bedarf es eines neuen aktuellen Tickets
