### ISSUE TITLE
Fehler bei der Ausführung des DB2Frontend-Skriptes (Schritt 5 und 6)

### ISSUE THREAD

**Issue by bejoe1** [medizininformatik-initiative/INTERPOLAR#346]
Bei Ausführung des D2Frontend-Skriptes (`docker compose run --rm --no-deps r-env Rscript R-db2frontend/StartDB2Frontend.R`) kommt folgender Fehler:

```r
Try to connect with: 
   dbname=cds_hub_db
   host=cds_hub
   port=5432
   user=db2frontend_user
   password=db2frontend
   schema=db2frontend_out
importRecords will change how it validates data in version 3.0.0.
We recommend preparing your data for import using castForImport .
Error in copyDB2Redcap() : 1 assertions failed:
 * The variable(s) record_id, patient_fe_id, pat_id, pat_cis_pid,
 * pat_name, pat_vorname, pat_gebdat, pat_aktuell_alter,
 * pat_geschlecht, patient_complete are not found in the project and/or
 * cannot be imported.
Calls: copyDB2Redcap ... <Anonymous> -> importRecords.redcapApiConnection -> <Anonymous>
Execution halted
``` 

Zur Info: ich habe heute den release-Branch getestet und alles nach Installationsanleitung neu aufgesetzt, inkl. der Datenbank.

**Comment by mayadogh** [comment]
@bejoe1 : es klingt nach einem Problem beim REDCap-Projekt. Folgendes kann ich mir als Problem vorstellen:

- das Projekt ist nicht richtig in REDCap implementiert
- API ist im Projekt nicht freigegeben / bzw. ist das Token oder die URL falsch in der .toml Datei

**Comment by mayadogh** [comment]
@bejoe1 : auch Issue #334 anschauen, vielleicht gibt es Gemeinsamkeinten.

**Comment by mayadogh** [comment]
@bejoe1 

- Das ist das richtige Projekt, ich würde nochmal trotzdem die URL kontrollieren falls der Port doch anderes ist oder sowas. 
- Sind Daten im Schema DB_out zu finden? Null Spalten sind kein Problem außer bei record_id.
- Im anderen Ticket hat man statt das API-Paket vom REDCap in R über httr & JSON Daten einlesen können. Warum das andere nicht funktioniert wissen wir immer noch nicht. Ob es Proxies seien oder sowas kann ich nicht sagen.

**Comment by mayadogh** [comment]
@bejoe1 Danke für das ausprobieren. REDCap war richtig verbunden, das ist gut. Das _out Schema was ich meinte war für das Frontend: db2frontend_out aber zuerst müssen die Schemata vorher auch Daten haben, dieses ist das letzte. Daher werde ich meine Kollegen zum Ticket assignen, damit sie schauen können was los ist. Ich glaube keine passenden Daten sind eingelesen.

**Comment by mayadogh** [comment]
@bejoe1 : es wird in den nächsten Tagen einen neuen Release geben. Es wird in der DIZ-Runde dazu weiteres gesagt.

**Comment by SebStaeubert** [comment]
@bejoe1 Hast dich das Problem mit Release v0.2.3 bei euch gelöst? Kann das Ticket geschlossen werden?

**Comment by astruebi** [comment]
Info: Der Fehler ließ sich dadurch beheben, dass ein unverändertes Redcap Projekt verwendet wurde. bejoe1 hatte in ihrem Redcap-Projekt eigentlich nur ein paar display-Optionen geändert (z.B. Tausendertrennzeichen, ...). Ohne diese Änderungen ging es.

Fazit: Das Ticket bleibt offen, bis wir die Ursache finden konnten. Wir werden auch bei uns mal solche eigentlich nur das Display betreffenden Änderungen vornehmen und damit versuchen den Fehler zu reproduzieren und dann geeignet zu behandeln. Ohne diese Behandlung wird es nicht möglich sein, dass ein DIZ ein vorhandenes und evtl. bereits geändertes Redcap einsetzt.

**Comment by SebStaeubert** [comment]
@SebStaeubert FAQ-Beitrag schreiben: Falls dieser Fehler auftritt, prüfen ob REDCap DB korrekt mit Default-Werten initialisiert wurde.

**Comment by SebStaeubert** [comment]
https://github.com/medizininformatik-initiative/INTERPOLAR/wiki/Frequently-Asked-Questions-%E2%80%90-FAQ#was-kann-ich-tun-wenn-der-fehler-error-in-db2frontendimportdb2redcap--1-assertions-failed-auftritt
