### ISSUE TITLE
Leserechte für Modul cds2db auf encounter Tabelle

### ISSUE THREAD

**Issue by Flow191** [medizininformatik-initiative/INTERPOLAR#348]
Modul cds2db braucht Leserechte auf View "v_encounter_all".

Danach kann Skript temp_Database_Access in cds2db gelöscht werden.

**Comment by SebStaeubert** [comment]
Im Moment ist ein Workaround aktiv.

**Comment by reuschem** [comment]
Erledigt cds2db_out hat benötigte Views
