### ISSUE TITLE
Tests für aktuellen Stand der DB(-Skripte)

### ISSUE THREAD

**Issue by SebStaeubert** [medizininformatik-initiative/INTERPOLAR#350]
Diese Fragen sollen adressiert werden:
- Funktionieren die Funktionen so wie sie sollen?
- Landen die richtigen Informationen im richtigen Feld?
- usw.

Tests sollen in einem eigenen Docker-Compose Setup ausgeführt werden.
Test zunächst manuell ausführen. Später mit Unit Tests implementieren, siehe #291

**Comment by reuschem** [comment]
Kleine Testskripte (ohne FHIR Daten) hinzugefügt um einzelne Funktionalitäten zu testen
