### ISSUE TITLE
Zuletzt gleichzeitig eingetroffene Datensätze zuverlässig erkennen

### ISSUE THREAD

**Issue by astruebi** [medizininformatik-initiative/INTERPOLAR#354]
Problem:
Datensätze, die schon einmal in der Datenbank vorkamen haben im Kern der Datenbank in der Spalte "last_check_date" einen anderen Zeitstempel als im selben Vorgang eingetroffene 'neue' (bisher nicht in der Datenbank vorkommende) Datensätze. Diese bekommen einen Zeitstempel in der Spalte "input_datetime" der minimal nach dem "last_check_date" der bereits bekannten Datensätze liegt.

Der R Code war bisher davon ausgegangen, dass diese beiden Zeitstempel identisch sind, um festzustellen, welche Information zu Patienten die aktuellste ist, Da das aber nicht so ist, werden immer nur die Daten (Patienten) gefunden, die neu sind.

Wir brauchen irgendeinen Indikator in der Datenbank, an dem wir die zuletzt gemeinsam eingetroffenen Datensätze in einer Tabelle und auch über Tabellengrenzen hinweg erkennen können.

**Comment by SebStaeubert** [comment]
Test mit @astruebi durchführen
