### ISSUE TITLE
DB Frontend - "Leere" RedCap Datensätze bei Kopierfunktion berücksichtigen und entfernen

### ISSUE THREAD

**Issue by reuschem** [medizininformatik-initiative/INTERPOLAR#369]
RedCap schreibt zu Instrumenten die noch nicht angelegt sind, diese trotzdem zu jedem Patienten einen Datensatz. Diese haben keinerlei Informationen und bedürfen nicht der Historisierung in der Datenbank.

**Comment by reuschem** [comment]
Es bedarf nochmal einer Analyse in welchen Feldern 1. Importierte 2. Leere RedCap 3. Gefüllte RedCap Datensätze unterscheiden - um mit Sicherheit richtig zu Filtern
Um keine Abhängigkeiten zu haben ist das Lösen von Issue #389 zuvor notwendig

**Comment by astruebi** [comment]
@reuschem Bitte lass uns mal besprechen, wo es sinnvoller ist, diese Datensätze zu 'behandeln'. Also ob schon in der db2frontend-Komponente oder erst in der DB.

**Comment by reuschem** [comment]
Bei erneuter Analyse zeigte sich das keine leeren Datensätze von RedCap in die Datenbank importiert werden. Es zeigt sich aber, auch das vermieden werden muss, das in RedCap Patienten oder Fälle angelegt werden können, da dann die Zuordnung im Nachhinein (Schreibeinschränkung in diesen Instrumenten) zu FHIR Daten nicht möglich ist.
