### ISSUE TITLE
Testdaten Apotheker exportieren und Test-Durchlauf

### ISSUE THREAD

**Issue by SebStaeubert** [medizininformatik-initiative/INTERPOLAR#379]
REDCap INTERPOLAR-Dev Projekt mit Daten der Apotheker exportieren und auf ip-VM importieren. Anschließend db2frontend aufrufen.

**Comment by SebStaeubert** [comment]
START
[TIME] 1725264072 2024-09-02 10:01:12
Run Import from Database to Frontend: RUNNING ...
Try to connect with:
   dbname=cds_hub_db
   host=cds_hub
   port=5432
   user=db2frontend_user
   password=db2frontend
   schema=db2frontend_out
SELECT record_id, record_id, patient_fe_id, pat_id, pat_cis_pid, pat_name, pat_vorname, pat_gebdat, pat_aktuell_alter, pat_geschlecht, patient_complete FROM v_patient
SELECT record_id, record_id, redcap_repeat_instrument, redcap_repeat_instance, patient_id_fk, fall_fe_id, fall_pat_id, fall_id, fall_studienphase, fall_station, fall_aufn_dat, fall_aufn_diag, fall_gewicht_aktuell, fall_gewicht_aktl_einheit, fall_groesse, fall_groesse_einheit, fall_status, fall_ent_dat, fall_complete FROM v_fall
Run Import from Database to Frontend: Error in redcapError(response, error_handling = "error") :
  400: ERROR: "429","redcap_repeat_instrument","Fall","redcap_repeat_instrument must be the unique form name of a Repeating Instrument. It currently does not match the unique form name of any Repeating Instruments.  Please fix this in the data import file and try again."
"429","patient_id_fk","429","This field ('patient_id_fk') does not exist on the Repeating Instrument named 'Fall'. You are not allowed to import data for this field into this Repeating Instrument."
"429","fall_fe_id","327","This field ('fall_fe_id') does not exist on the Repeating Instrument named 'Fall'. You are not allowed to import data for this field into this Repeating Instrument."
"429","fall_pat_id","UKB-0001","This field ('fall_pat_id') does not exist on the Repeating Instrument named 'Fall'. You are not allowed to import data for this field into this Repeating Instrument."
"429","fall_id","UKB-0001-E-1","This field ('fall_id') does not exist on the Repeating Instrument named 'Fall'. You are not allowed to import data for this field into this Repeating Instrument."
"429","fall_station","Station 2","This field ('fall_station') does not exist on the Repeating Instrument named 'Fall'. You are not allowed to import data for this field into this Repeating Instrument."
"429","fall_aufn_dat","2020-07-30","This field ('fall_aufn_dat') does not exist on the Repeating Instrument named 'Fall'. You are not allowed to import data for this field into this Repeating Instrument."
"429","fall_aufn_diag","Akute Pankreatitis","This field ('fall_aufn_diag') does not exist on the Repeating Instrument named 'Fall'. You are not allowed to import data for this field into this Repeating Instrument."
"429","fall_status","finished","This field ('fall_status') does not exist on the Repeating Instrument named 'Fall'. You are not allowed to import data for this field into this Repeating Instrument."
"429","fall_ent_dat","2020-08-14","This field ('fall_ent_dat') does not exist on the Repeating Instrument named 'Fall'. You are not allowed to import data for this field into this Repeating Instrument."
"429","fall_complete","2","This field ('fall_complete') does not exist on the Repeating Instrument named 'Fall'. You are not allowed to import data for this field into this Repeating Instrument."
"437","redcap_repeat_instrument","Fall","redcap_repeat_instrument must be the unique form name of a Repeating Instrument. It currently does not match the unique form name of any Repeating Instruments.  Please fix this in the data import file and try again."
"437","patient_id_fk","437","This field ('patient_id_fk') does not exist on the Repeating Instrument named 'Fall'. You are not allowed to import data for this field into this Repeating Instrument."
"437","fall_fe_id","361","This field ('fall_fe_id') does not exist on the Repeating Instrument named 'Fall'. You are not allowed to import data for this field into this Repeating Instrument."
"437","fall_pat_id","UKE-0015","This field ('fall_pat_id') does not exist on the Repeating Instrument named 'Fall'. You are not allowed to import data for this field into this Repeating Instrument."
"437","fall_id","UKE-0015-E-1","This field ('fall_id') does not exist on the Repeating Instrument named 'Fall'. You are not allowed to import data for this field into this Repeating Instrument."
"437","fall_station","Station 2","This field ('fall_station') does not exist on the Repeating Instrument named 'Fall'. You are not allowed to import data for this field into this Repeating Instrument."
"437","fall_aufn_dat","2020-07-31","This field ('fall_aufn_dat') does not exist on the Repeating Instrument named 'Fall'. You are not allowed to import data for this field into this Repeating Instrument."
"437","fall_aufn_diag","Herzinsuffizienz","This field ('fall_aufn_diag') does not exist on the Repeating Instrument named 'Fall'. You are not allowed to import data for this field into this Repeating Instrument."
"437","fall_status","finished","This field ('fall_status') does not exist on the Repeating Instrument named 'Fall'. You are not allowed to import data for this field into this Repeating Instrument."
"437","fall_ent_dat","2020-08-05","This field ('fall_ent_dat') does not exist on the Repeating Instrument named 'Fall'. You are not allowed to import data for this field into this Repeating Instrument."
"437","fall_complete","2","This field ('fall_complete') does not exist on the Repeating Instrument named 'Fall'. You are not allowed to import data for this field into this Repeating Instrument."
END

**Comment by SebStaeubert** [comment]
Run Import from Frontend to Database: Error : Failed to initialise COPY : ERROR:  column "fall_zimmernr" of relation "fall_fe" does not exist

**Comment by reuschem** [comment]
Daten wurden exportiert und an Frau Beppler übergeben.
