### ISSUE TITLE
DB-Export für Biometriker

### ISSUE THREAD

**Issue by SebStaeubert** [medizininformatik-initiative/INTERPOLAR#380]
- [ ] Dokumentation der Anforderungen (nach Vorgaben T.Beppler (siehe Mail))
- [ ] Export-Script

Nachdem #379 abgearbeitet ist.

**Comment by SebStaeubert** [comment]
Run Import from Frontend to Database: Error : Failed to initialise COPY : ERROR:  column "redcap_repeat_instrument" of relation "patient_fe" does not exist

**Comment by reuschem** [comment]
Ein Testdatensatz wurde an Frau Beppler ausgegeben und dieses Ticket kann damit geschlossen werden.
Eine Überarbeitung der zur Verfügung zu stellenden Daten ist Wahrscheinlich und wird in einem Zukünftigen Ticket berücksichtigt.
