### ISSUE TITLE
Im- und Export von redcap_repeat_instrument zum und vom RedCap - Gross/Kleinschreibung

### ISSUE THREAD

**Issue by reuschem** [medizininformatik-initiative/INTERPOLAR#389]
Es hat sich gezeigt das RedCap in jedem repeating Instrument das es importiert die Spalte redcap_repeat_instrument erwartet mit der Bezeichnung des Instrumentes. Am Beispiel Fall haben wir festgestellt das die klein als "fall" sein muss.

Beim Export der Daten zur Datenbank wird das Instrument groß geschrieben ausgegeben "Fall".

Dies führt zu doppelten Datensätzen.

Daher bitte klären wie RedCap intern mit dem Feld umgeht und welchen Wert es erwartet bzw. zurück schreibt.

**Comment by mayadogh** [comment]
es ist wie du es beschreibst @reuschem : beim zurück schreiben ist Fall so, beim einlesen muss er fall heißen, WEIL: in der DB anscheinend sind Instrumentennamen alle kleine geschrieben, aber was wir im Instrument im REDCap sehen ist der label und ist wie der Nutzer das Instrument bennant hat. Also, ich habe Fall so geschrieben: Fall.

**Comment by MarcelvonBorzestowski** [comment]
Die Instrumenten Bezeichnung von redcap_repeat_instrument wird in der Tat groß geschrieben, wobei ja die "Variablenform" der Instrumentenbezeichnung klein geschrieben. 

![image](https://github.com/user-attachments/assets/3b975ebe-9400-480b-bdfd-93c2d396c6c9)

![image](https://github.com/user-attachments/assets/c0016994-42bf-46c5-b64e-28f544a81d49)

**Comment by reuschem** [comment]
Die Frage ist nun, welche Bezeichnung muss beim Importieren und Exportieren der Daten in redcap_repeat_instrument stehen und warum sind diese gegeben falls unterschiedlich. Bzw. kann man dies einstellen?

**Comment by MarcelvonBorzestowski** [comment]
In einem anderen Projekt funktioniert der Import klein 

![image](https://github.com/user-attachments/assets/ed01a470-c453-412c-b412-6b159d8ec813)

Eine variable Einstellung in REDCap ist mir nicht bekannt.

**Comment by MarcelvonBorzestowski** [comment]
Unabhängig von der Darstellung (groß) oben in der REDCap-Reportansicht werden die Instrumente in den Exporten klein bezeichnet.

**Comment by reuschem** [comment]
Das es beim Import klein geschrieben, sprich der "Form Name" sein muss ist schon klar.
Gestern hat es aber anscheinend das "Instrument" und nicht den "Form Name" beim Export verwendet. Die Frage ist, was ist an diesem Projekt anders, als an den anderen dir bekannten Projekten?
Ist es der selbe Weg eines Exports?

**Comment by MarcelvonBorzestowski** [comment]
Wie [mayadogh](https://github.com/mayadogh) ja oben sagte, sehen wir komischerweise das Label (also Instrument) in der Spalte redcap_repeat_instrument in der Exportansicht innerhalb REDCap. In der Exportdatei wird der (relevante) Form Name richtigerweise in dieser Spalte angegeben. Wäre daher nicht eher die Frage worauf das Exportskript zugreift?

Vielleicht lässt es sich an mit diesem präzisieren?!

![image](https://github.com/user-attachments/assets/3d9a3865-e554-4828-b8bf-23fffdf75da2)
