### ISSUE TITLE
"No Encounters found for ward(s) 'XXX' on FHIR server for timestamp 2020-07-31T21:25:00."

### ISSUE THREAD

**Issue by vicho001** [medizininformatik-initiative/INTERPOLAR#396]
Hallo, wir aus dem Standort Essen haben den neuen Release bei uns neu getestet und sind auf das folgende Problem gestoßen:
`No Encounters found for ward(s) 'XXX' on FHIR server for timestamp 2020-07-31T21:25:00.`

Wir vermuten, dass es an der relativen Referenz bei uns liegt, aber eine logische Referenz erwartet wird. [https://build.fhir.org/references.html]

<img width="1057" alt="Bildschirmfoto 2024-09-06 um 11 47 08" src="https://github.com/user-attachments/assets/97f7a280-f854-4346-85ac-9294668c3f29">

**Comment by astruebi** [comment]
Es werden nur Encounter gefunden, die zum aktuellen Filter passen (ENCOUNTER_FILTER_PATTERN_X in der [cds2db_config.toml des release Branches](https://github.com/medizininformatik-initiative/INTERPOLAR/blob/5e7e96a9154076406b3fe4d9649e6e7455ecf4aa/R-cds2db/cds2db_config.toml#L107)).

Außerdem wird per Default nach Encountern gesucht, deren Startdatum nach dem aktuellen Datum liegt und deren Status "in-progress" ist.

Das aktuelle Datum scheint hier mit dem toml-Parameter [DEBUG_CURRENT_DATETIME](https://github.com/medizininformatik-initiative/INTERPOLAR/blob/5e7e96a9154076406b3fe4d9649e6e7455ecf4aa/R-cds2db/cds2db_config.toml#L83C2-L83C25) auf ein Datum in der Vergangenheit gesetzt zu sein.

Ob der andere Debug Parameter [DEBUG_ENCOUNTER_STATUS](https://github.com/medizininformatik-initiative/INTERPOLAR/blob/5e7e96a9154076406b3fe4d9649e6e7455ecf4aa/R-cds2db/cds2db_config.toml#L89C2-L89C24) auch aktiviert wurde, so dass Encounter gefunden werden, die bereits "finished" als Status haben, ist nicht ersichtlich.  Welchen Status der oben abgebildete Encounter hat, kann ich auch nicht erkennen.

Wir haben aktuell genau diese Möglichkeiten zur DEBUG-Analyse von Daten aus der Vergangenheit verfeinert. Diese Änderungen sind noch nicht im 'release'-Branch, sondern nur im 'develop'. Bitte mal diesen Branch auschecken und testen.

Dabei ist es jetzt möglich, sehr feine Einstellungen vorzunehmen, insbesondere um Altdaten testweise zu laden. 
Siehe [cds2db_config.toml des develop Branches](https://github.com/medizininformatik-initiative/INTERPOLAR/blob/10a6e32afd650854198bd8346b2b63f2c1cf855c/R-cds2db/cds2db_config.toml#L73)
Jeder Parameter sollte eindeutig beschrieben sein. Einige haben Abhängigkeiten von anderen Debug-Parametern.

**Comment by SebStaeubert** [comment]
Keine Rückmeldung, Ticket wird geschlossen und kann ggf. wieder geöffnet werden.

**Comment by vicho001** [comment]
Das Problem besteht immernoch, da das Problem nicht an dem Startdatum liegt, sondern an der relativen Referenz bei uns im Standort.
Die Station wo der Patient liegt, liegt in einer Location Ressource, d.h. es steht nicht direkt im Encounter.
