### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by vicho001** [medizininformatik-initiative/INTERPOLAR#397]
Hallo, wir sind vom Standort Essen und wünschen uns eine bessere Logging bezüglich des Problems #396 und haben eine Vermutung woran es legen kann. Um das Problem zu beheben, wäre es gut wenn in dem Logging die genauen FHIR-Abfragen drin stehen welche in den FHIR-Server gesendet werden. 
Ich habe ein neues Issue erstellt, da das letzte Issue #334 zu unübersichtlich wurde.

**Comment by Flow191** [comment]
Hallo, die FHIR-Requests sollten in den entsprechenden logging-Dateien in dem Ordner "outputLocal/cds2db/log" hinterlegt sein, wenn das verbose-level (Anpassbar in der cds2db_config.toml) auf mindestens 9 gesetzt ist. Eine genaue Auflistung der FHIR-Requests der einzelnen Ressourcen sind auch unter "outputLocal/cds2db/bundles" zu finden. Es werden unter "outputLocal" immer die letzten 5 Läufe der einzelnen Komponenten gespeichert, wobei der aktuellste Lauf kein Zeitstempel im Namen hat.

**Comment by SebStaeubert** [comment]
Keine Rückmeldung, Ticket wird geschlossen und kann ggf. wieder geöffnet werden.

**Comment by vicho001** [comment]
Hallo, wir haben hier ein neues Problem, nachdem wir Verbose = 9 gesetzt haben:
<img width="1413" alt="Bildschirmfoto 2024-10-11 um 15 05 48" src="https://github.com/user-attachments/assets/3275cc37-b7a1-4545-830e-6a09f3178979">
<img width="977" alt="Bildschirmfoto 2024-10-11 um 15 06 20" src="https://github.com/user-attachments/assets/cc24f3ae-de12-43c5-80b7-1e3ddb817674">
