### ISSUE TITLE
Ist Frontend auf Aktuellen Stand - Frage aus München

### ISSUE THREAD

**Issue by reuschem** [medizininformatik-initiative/INTERPOLAR#429]
Bei einem Online Treffen mit dem DIZ München ist im RedCap Projekt aufgefallen (Carolin Schmidt) das es unter individualisierte Dashboards noch Grafiken zu Leberinsuffizienz usw. gibt. Die Apotheker waren darüber erstaunt. Bitte nochmal Doku Joachim K. prüfen und mit aktuellen Stand RedCap Projekt abgleichen.

**Comment by MarcelvonBorzestowski** [comment]
Das Dashboard ist ein Relikt und für die Programmstruktur völlig irrelevant. Kann gelöscht werden.
