### ISSUE TITLE
REDCap Projekt adjustieren

### ISSUE THREAD

**Issue by mayadogh** [medizininformatik-initiative/INTERPOLAR#44]
z.B. Arme / Events usw. definieren

**Comment by mayadogh** [comment]
Inhaltliche Entscheidung steht noch aus.

**Comment by SebStaeubert** [comment]
@mayadogh kann das Ticket Milestone "Release v0.2.0" zugeordnet werden? Ist es bereits abgeschlossen?

**Comment by mayadogh** [comment]
Wir müssen gemeinsam überlegen ob REDCap eigene Milestones hat (sowas wie: Definition des Frontends / Interventions)...
Dieses Issue ist fertig gemacht.
