### ISSUE TITLE
Melting dauert zu lange

### ISSUE THREAD

**Issue by KoesterH** [medizininformatik-initiative/INTERPOLAR#441]
Beim Ausführen auf einem produktiven FHIR-Server, werden pro Patient viele Observations gefunden. Dadurch dauert das Melting selbst bei 35 Patienten ~ 7 Stunden.

**Comment by SebStaeubert** [comment]
Optimierungen beim "FHIR Melt" sind in Arbeit.

**Comment by SebStaeubert** [comment]
- [ ] lokale Änderungen Dockerfile (Entwicklungsversion FHIRCrackR verwenden) in Feature-Branch -> develop -> release hinzufügen
