### ISSUE TITLE
Error column "na" does not exist in Dataprocessor

### ISSUE THREAD

**Issue by KoesterH** [medizininformatik-initiative/INTERPOLAR#442]
Nachdem die Datenbank vollständig gelöscht wurde (Volume gelöscht) läuft das Retrieval im ersten Lauf nur unvollständig durch. Dabei wirft es aber keinen Fehler. Wird anschließend der Dataprocessor ausgeführt beendet er sich mit dem Fehler: 
Error : Failed to prepare query : ERROR:  column "na" does not exist LINE 2:  WHERE last_processing_nr = NA
Wird anschließend das Retrieval nochmal gestartet (mit den gleichen Einstellungen), läuft es korrekt durch und auch der Fehler im Dataprocessor tritt dann nicht mehr auf.

**Comment by Flow191** [comment]
Der Fehler tritt nur auf, wenn die Datenbank neu aufgesetzt wurde und der Dataprocessor zu schnell nach dem cds2db aufgerufen wird. Es muss mindestens eine Minute gewartet werden, damit die Cron-Jobs korrekt durchgelaufen sind. Habe diese Info entsprechend in die Error-Ausgabe gepackt.
