### ISSUE TITLE
alt Daten lassen sich nicht löschen?

### ISSUE THREAD

**Issue by KoesterH** [medizininformatik-initiative/INTERPOLAR#443]
Die Daten aus dem RedCap-Projekt wurden gelöscht (Erase Data) und auch das Volume der Interpolardatenbank. Anschließend wurden die Strecken mit einem komplett neuen Zeitraum ausgeführt. Nach dem Durchlaufen aller Strecken finden sich in RedCap neben den korrekten (neuen) Patienten auch immer noch die alten Patienten aus der Testphase.

**Comment by SebStaeubert** [comment]
Hast Du geprüft, ob das mit der CDS Tool Chain verknüpfte REDCap Projekt (Token!) tatsächlich keine Records mehr enthält?
Besteht das Problem noch?

**Comment by SebStaeubert** [comment]
@reuschem kann es sein, dass in REDCap gelöschte Patienten erneut hinzugefügt werden, z.B. falls in der DB aktualisierte Daten hinzugekommen sind?

**Comment by KoesterH** [comment]
Ein wenig off-Topic: was muss generell erfüllt sein, damit ein Patient nicht mehr im Dashboard erscheint? oder bleiben die Patienten wenn sie einmal da sind, für immer da?
Ich hatte bei den alten Patienten mit abgeschlossenem Fall eine abgeschlossene Medikationsanalyse angelegt aber trotzdem sind die Patienten noch im Dashboard auf erster Position gelistet.

**Comment by SebStaeubert** [comment]
Die Anzeige im REDCap erfolgt je nach dem, welcher Filter ausgewählt ist.
Nutzt Du die Filter?
In REDCap gibt es aktuell einen Bug bei den Dashboard-Filtern. Diese werden zwar mit dem XML-Import importiert aber sind noch nicht aktiv. Ist es evtl. dieses Problem?

**Comment by KoesterH** [comment]
danke, ja das war auch ein Problem und funktioniert mittlerweile. 
Mit den Filtern ist es jetzt auch kein weiteres Problem, dass im default immer alles angezeigt wird.
