### ISSUE TITLE
Mehrfacher Download bekannter FHIR Ressourcen verhindern

### ISSUE THREAD

**Issue by Flow191** [medizininformatik-initiative/INTERPOLAR#447]
FHIR-Serach Parameter `_lastUpdated` mit in der FHIR-Abfrage mit einbauen und das Datum aus Datenbank holen.

**Comment by SebStaeubert** [comment]
Diskussionsstand 04.11.2024 (IP-IT Runde):
Tabelle pids_per_ward sollte erfassen/speichern, dass ein Patient entlassen wurde. Ggf. diese Tabelle bzw. die Information bei der Abfrage nach Daten von Patienten, die laut DB noch einen offenen Fall haben aber nicht mehr auf einer IP-Station liegen. Ggf. weiter durchdenken.

**Comment by reuschem** [comment]
Idee der Lösung beim laden der FHIR-Daten:
- für jeden Pat :  in der jeweiligen Res. : gibt es neue FHIR-Daten mit angegebenem Zeitraum oder nicht
  -> ja : -> lade alle Daten zu dem Patienten neu herunter (Zieltabelle - R)
  -> nein : -> lade die letzten raw Daten aus der DB und füge diese in der Liste zu (Zieltabelle - R) mit ein
- füge alle Datensätze in einem Zug in die DB

**Comment by SebStaeubert** [comment]
Siehe auch #471

**Comment by Flow191** [comment]
Merged in branch #479
