### ISSUE TITLE
REDCap Reports erzeugen

### ISSUE THREAD

**Issue by mayadogh** [medizininformatik-initiative/INTERPOLAR#45]

**Comment by mayadogh** [comment]
Erste Gedanken vom MLö:
[INTERPOLAR COCKPIT_v3.docx](https://github.com/medizininformatik-initiative/INTERPOLAR/files/14406418/INTERPOLAR.COCKPIT_v3.docx)

**Comment by SebStaeubert** [comment]
@mayadogh Milstone "Release v0.2.0"?

**Comment by mayadogh** [comment]
#59 ersetzt dies hier.
