### ISSUE TITLE
Referenzen in den Spalten-Namen der IP-DB nicht mehr _id sondern _ref nennen

### ISSUE THREAD

**Issue by astruebi** [medizininformatik-initiative/INTERPOLAR#453]

**Comment by SebStaeubert** [comment]
- [ ] Hinweis in den Release-Notes: breaking change!

**Comment by reuschem** [comment]
Ist die Umbenennung auch für die "*_fe" - Tabellen gedacht/gemeint - dann müssen wir auch die Benennung im Frontend ändern?
@MarcelvonBorzestowski

**Comment by MarcelvonBorzestowski** [comment]
Habe ich am Montag in der IT-Runde auch gefragt. Antwort war, dass das mit dem Frontend nichts zu tun habe. Könnte man aber er Einheitlichkeit wegen von mir aus machen.

**Comment by Flow191** [comment]
Ganz am Ende, kurz vor Release implementieren.
