### ISSUE TITLE
Datumsangaben in RedCap sind um einen Tag falsch

### ISSUE THREAD

**Issue by KoesterH** [medizininformatik-initiative/INTERPOLAR#459]
Das Geburtsdatum der Patienten sowie das Aufnahmedatum beim Fall sind in sehr vielen Fällen um einen Tag falsch (-1 Tag im Vergleich zu dem was sein sollte). In der Interpolardatenbank in der db_log Tabelle stehen die Daten aber richtig drin. Sie werden nur in RedCap falsch angezeigt.

**Comment by SebStaeubert** [comment]
Welche Version nutzt du? Wir hatten dieses Problem schon einmal und es wurde durch setzen entspr. locales in der DB connection, die R aufbaut, gelöst.

**Comment by KoesterH** [comment]
momentan habe develop Version. Allerdings nicht ganz die aktuellste sondern den Stand von damals als ihr das mit der Suche nach IMP gleich am Anfang implementiert hattet.

**Comment by SebStaeubert** [comment]
Ok, dann kann es sein, dass der Fix bei Dir noch nicht aktiv ist.
Spricht etwas gegen ein 'git pull'? :-)

**Comment by KoesterH** [comment]
nein, mach ich morgen und berichte ob es geholfen hat :-)

**Comment by KoesterH** [comment]
ist mit der aktuellen Version jetzt behoben. Danke
