### ISSUE TITLE
FHIR2SQL Initiale R-Projektstruktur anlegen

### ISSUE THREAD

**Issue by Flow191** [medizininformatik-initiative/INTERPOLAR#46]

**Comment by SebStaeubert** [comment]
Zur Info "SQLon FHIR":

- https://github.com/FHIR/sql-on-fhir (deprecated)
- https://github.com/FHIR/sql-on-fhir-v2/ (v2)
- https://build.fhir.org/ig/FHIR/sql-on-fhir-v2/
