### ISSUE TITLE
RedCap-Spalten in den gefilterten Ansichten 

### ISSUE THREAD

**Issue by KoesterH** [medizininformatik-initiative/INTERPOLAR#461]
Wenn in RedCap nach irgendwas gefiltert wird (z.B. nicht abgeschlossene Fälle, siehe Bild) dann wird nur die erste Spalte mit dem Patienten angezeigt. Hier sollten besser auch alle Spalten angezeigt werden die in der Dashboard default Ansicht zu sehen sind. 
![RedCap_Spalten](https://github.com/user-attachments/assets/1c651faf-716c-4a9e-bc40-4540644711a6)

**Comment by MarcelvonBorzestowski** [comment]
Auf der Dev-Instanz funktioniert es anstandslos. Sind Formulare bereits angelegt bzw. gibt es nicht abgeschlossene Fälle in den Datensätzen?

![image](https://github.com/user-attachments/assets/b0f33d7b-b3ed-4b7f-be28-4cf72a92a40d)

**Comment by KoesterH** [comment]
Ja es gibt da da sowohl nicht abgeschlossene Fälle wie auch angelegte Medikationsanalysen. In der nicht gefilterten Ansicht sieht es so aus: 
![image](https://github.com/user-attachments/assets/9b28d750-1b5d-433b-8a3a-f1caf236d4d8)
komisch, dass es bei euch funktioniert. Kann es vielleicht irgendwie an der RedCap-Version liegen? Ich nutzte nicht das RedCap das mitkommt sondern unsere eigene Instanz

**Comment by MarcelvonBorzestowski** [comment]
Dann müssen wir den Filter anschauen. So müsste es aussehen:

![image](https://github.com/user-attachments/assets/e301e917-5501-4ddb-8db7-84458d30f315)

In nächsten Schritt können wir auch noch die Instrumentenbezeichnung im Codebook überprüfen:

![image](https://github.com/user-attachments/assets/30cab8c1-e2e7-4b36-8714-953577b69b03)

**Comment by KoesterH** [comment]
der Filter sieht bei mir genauso aus wie bei dir. Bei der Instrumentenbezeichnung weiß ich nicht wo ich die finde.
Hast du Zeit für ein kurzes Meeting?

**Comment by MarcelvonBorzestowski** [comment]
Ja, geht.

**Comment by MarcelvonBorzestowski** [comment]
Du hast doch noch den IP-BBB-Link?!

**Comment by KoesterH** [comment]
ja ich such in gerade

**Comment by MarcelvonBorzestowski** [comment]
Es scheint ein nicht weiter spezifizierbares Übertragungsproblem zwischen REDCap-Instanzen zu sein. In diesem Fall wird die standorteigene REDCap-Instanz statt der mitgelieferten IP-Version genutzt.

Die Lösung des Problems war eine Reevalierung der Filter logic; im Editor muss unten in grün "Valid" erscheinen. Danach funktioniert der Filter wie vorgesehen.

![image](https://github.com/user-attachments/assets/e5c08154-7215-42b5-92a8-9e2a5c47402b)

![image](https://github.com/user-attachments/assets/95f9b30f-432e-4aa1-b82c-fb98f7dd9ef2)
