### ISSUE TITLE
Filteroption nach jeder Ressource

### ISSUE THREAD

**Issue by vicho001** [medizininformatik-initiative/INTERPOLAR#463]
Hallo, wir sind vom Standort Essen. Derzeit besteht nur die Möglichkeit, nach Encounter zu filtern. Es wäre jedoch sehr hilfreich, wenn auch ein Filter nach spezifischen Ressourcen (pro Ressource) möglich wäre. Wäre dies umsetzbar?
Wir würden es außerdem begrüßen, wenn die tatsächlich gesendeten (rohen) requests an den FHIR Server im Debug Level mit in den Log aufgenommen werden können.

**Comment by Flow191** [comment]
Hallo, wir haben bereits für das nächste Release die Möglichkeit vorgesehen in der cds2db config-toml für jede Ressource einzeln oder für alle zusammen an die FHIR-request noch zusätzliche Parameter anzuhängen. Die requests sollten in der log-Datei vorhanden sein, oder noch besser einsehbar in dem Unterordner "bundles" auf der gleichen Ebene, wo auch der "log"-Ordner liegt. Dort sind die FHIR-requests nach Ressourcen hinterlegt.

**Comment by Flow191** [comment]
Wenn es hierzu erstmal keine Frage mehr gibt, schließe ich das Issue.
