### ISSUE TITLE
Warteschleife am Ende von cds2db integrieren

### ISSUE THREAD

**Issue by Flow191** [medizininformatik-initiative/INTERPOLAR#466]
Damit alle Daten in die Datenbank geschrieben werden, brauchen wir am Ende von cds2db noch eine Warteschleife. Damit ist sichergestellt, dass wenn dann sofort der dataprocessor gestartet wird, dass dieser auch die Elemente aus der DB bekommt.

**Comment by SebStaeubert** [comment]
gelöst durch #471
