### ISSUE TITLE
Toolchain hängt sich auf

### ISSUE THREAD

**Issue by KoesterH** [medizininformatik-initiative/INTERPOLAR#468]
Hi bei mir hat sich die Toolchain jetzt 3x hintereinander bei folgendem Schritt aufgehängt:
![image](https://github.com/user-attachments/assets/c95326b2-6dfc-47f2-9977-06881b2cbd18)
irgendwelche Ideen woran das liegen könnte? Es kommt kein Fehler aber es läuft über Stunden nicht weiter

**Comment by KoesterH** [comment]
Das tritt auf, seit ich die Images mit der develop Version neu gebaut habe. Wenn ich das richtig gesehen habe, ist da auch die Verbesserung vom fhir-melt mit dabei. 
Da direkt danach eigentlich das Melting kommen sollte, denke ich dass es irgendwie damit zusammenhängt.
Eine Idee wie ich das fixen kann, wäre wirklich schön, weil so kann ich im Moment nichts neues ausleiten

**Comment by Flow191** [comment]
@reuschem Also im cds2db nehmen wir jetzt das Löschen der Tabelleninhalte der raw-Tabellen raus. Wie sieht das bei den Tabellen für das Frontend aus? Da löschen wir die Inhalte von fall_fe und patient_fe momentan auch noch. Ist das noch relevant?

**Comment by Flow191** [comment]
Hier sollte sich jetzt auch alles gekärt haben. Ich schließe das Issue.
