### ISSUE TITLE
row count > 0 : argument is of length 0

### ISSUE THREAD

**Issue by KoesterH** [medizininformatik-initiative/INTERPOLAR#476]
Beim schreiben der raw Tabellen in die Datenbank bekomme ich folgenden Fehler:
Error in if (row_count > 0) { : argument is of length zero

Das passiert nachdem er  pids_per_ward eingefügt hat. Danach wären die Locations dran. Demnach denke ich, dass der Fehler beim Versuch die Locations zu schreiben auftritt. 
Jetzt ist es leider so, dass mein aktuell verwendeter FHIR-Server keine Locations enthält. Das heißt die Links im Encounter laufen ins Leere. 

daher zwei Fragen:
liegt es (vermutlich) tatsächlich an den fehlenden Locations?
und wenn ja kann man dem Skript sagen, dass es an dieser Stelle tolerant sein soll? 
![image](https://github.com/user-attachments/assets/47f6d06e-69b6-4d7d-ad1c-c84694002915)

**Comment by Flow191** [comment]
Wir haben den Code bereits angepasst, der dazugehörige branch ist aber noch nicht im develop. Wir fragen jetzt ab, ob es Tabellen gibt, die in die Datenbank geschrieben werden sollen, aber nicht in der Datenbank vorhanden sind. Ich denke dadurch kommt der Fehler zustande. Das es nicht alle Ressourcen auf dem FHIR Server gibt, wird sowieso schon abgefangen, bzw. sind die Tabellen dann leer. In der Datenbank wird sich in Kürze auch noch bisschen was ändern, die muss dannn sowieso nochmal aufgesetzt werden. Wenn du jetzt sofort was testen möchtest, kannst du den Branch #472 versuchen, da sind die Änderungen schon drin.
