### ISSUE TITLE
Aktive Patienten werden nicht gefunden

### ISSUE THREAD

**Issue by KoesterH** [medizininformatik-initiative/INTERPOLAR#481]
Bei der initialen Datenbankabfrage werden korrekt 36 Patienten gefunden. 
Etwas später kommt aber dieser Fehler, dass keine aktiven Patienten gefunden werden konnten:

SELECT enc_patient_id FROM v_encounter
   WHERE enc_period_start <= '2024-11-21 07:34:26' AND
   (enc_period_end is NULL OR enc_period_end > '2024-11-21 07:34:26') ; 
Download and crack resources by Patient IDs per ward: Error in loadResourcesByPatientIDFromFHIRServer(patient_ids_per_ward,  : 
  No active patient IDs in encounter table found in database. Please check FHIR-search parameter for encounter in toml-file.

Die aktuellen gefundenen Encounter haben kein Enddatum. Daher sollte die WHERE Bedingung eigentlich erfüllt sein. 
Momentan habe ich den branch 472 bei mir ausgechecked.

**Comment by astruebi** [comment]
Duplicate zu #479 

Wir sind dran. Ich muss das noch testen.
