### ISSUE TITLE
pg_cron/pg_background shared memory ERROR

### ISSUE THREAD

**Issue by SebStaeubert** [medizininformatik-initiative/INTERPOLAR#501]
per pg_cron aufgerufene pg_background Befehle führen zu einer ERROR-Meldung. Das Ergebnis der Ausführung stimmt jedoch.
> ERROR:  unable to map dynamic shared memory segment

Ursache (inkl. Lösungsansätze) ist vermutlich hier beschrieben: https://github.com/vibhorkum/pg_background/issues/1

**Comment by SebStaeubert** [comment]
@reuschem Wo muss die Pause gemacht werden?
Commit?

**Comment by reuschem** [comment]
In der Funktion die vom cron-job mit jeder Instanz aufgerufen wird - in welcher größere backround Prozesse aufgerufen werden, sollte am Anfang die Pause eingebaut werden bis der dsms bereit steht . (in unserem Projekt db.cron_job_data_transfer() )
