### ISSUE TITLE
Fall ID und Patienten ID richtig setzen in Redcap

### ISSUE THREAD

**Issue by Flow191** [medizininformatik-initiative/INTERPOLAR#507]
- In Redcap steht als Fall ID die FHIR-ID drin und nicht der Identifier
- In Redcap steht als Patient ID der falsche Identifier drin

**Comment by Flow191** [comment]
@KoesterH Ich habe jetzt nachvollzogen warum bei euch nicht der korrekte Identifier für die Patienten in Redcap angezeigt werden. Es gibt in der config toml Datei vom dataprocessor drei Parameter. `FRONTEND_DISPLAYED_PATIENT_FHIR_IDENTIFIER_SYSTEM`, `FRONTEND_DISPLAYED_PATIENT_FHIR_IDENTIFIER_TYPE_SYSTEM` und `FRONTEND_DISPLAYED_PATIENT_FHIR_IDENTIFIER_TYPE_CODE`. Über diese Parameter kannst du steuern, welche Identifier zulässig sind. z.B. könntest du FRONTEND_DISPLAYED_PATIENT_FHIR_IDENTIFIER_TYPE_CODE = "^MR$" aktivieren, um für Patienten nur den Identifier type code "MR" zuzulassen. Ich glaube danach wolltest du auch filtern, oder? Die Parameter sind bereits eine Weile im Code, hatte ich bei unseren Gespräch leider nicht parat. Aber daran hatten wir schon gedacht.

**Comment by KoesterH** [comment]
Danke!

**Comment by KoesterH** [comment]
Danke, hab ich ausprobiert und funktioniert jetzt einwandfrei
