### ISSUE TITLE
"Cockpit" Version 1.0 in REDCap erstellen

### ISSUE THREAD

**Issue by mayadogh** [medizininformatik-initiative/INTERPOLAR#59]
- [ ] [Vorhandene Doku (SharePoint)](https://tmfev.sharepoint.com/:w:/r/sites/tmf/mi-i/_layouts/15/Doc.aspx?sourcedoc=%7B71C7671D-3E62-4145-AC6C-5E8CB2B3E119%7D&file=Beschreibung-REDCap-Frontend.docx&action=default&mobileredirect=true) in Markdown Datei im Verzeichnis REDCap-frontend überführen.

**Comment by mayadogh** [comment]
Erstes Konzept von MLö an mir geschickt, muss bearbeitet werden...

**Comment by mayadogh** [comment]
Erste Gedanken vom MLö :
[INTERPOLAR COCKPIT_v3.docx](https://github.com/medizininformatik-initiative/INTERPOLAR/files/14406393/INTERPOLAR.COCKPIT_v3.docx)

**Comment by SebStaeubert** [comment]
@mayadogh Milstone "Release v0.2.0"?

**Comment by mayadogh** [comment]
Milestone für Release v0.2.0 muss in Absprache mit MLö definiert werden.
