### ISSUE TITLE
Prüfen, wie die Aktualisierung in den Arzneimittelverordnungssystemen und deren CDSS in der KH-IT funktioniert

### ISSUE THREAD

**Issue by SebStaeubert** [medizininformatik-initiative/INTERPOLAR#6]
Prüfen, wie die Aktualisierung in den Arzneimittelverordnungssystemen und deren CDSS in der KH-IT funktioniert (SStäubert, FMeineke, DNeumann)

**Comment by neumdan** [comment]
Erledigt. Es werden die Listen für das CDSS von MII, Vidal, Diagnosa herangezogen und dargestellt.
Die Anbindung der CPOE funktioniert direkt an die Patientenakte. Es werden dedizierte Patienten aufgerufen und deren Informationen werden dann aus der Akte gezogen.
