### ISSUE TITLE
Prüfen der Funktionsweise des AIDKlinik m. Heidelberg

### ISSUE THREAD

**Issue by SebStaeubert** [medizininformatik-initiative/INTERPOLAR#7]
Prüfen der Funktionsweise des AIDKlinik m. Heidelberg (Ffitz-Kebede, Hseidling, SStäubert, FMeineke, DNeumann)

**Comment by neumdan** [comment]
AIDKlinik ist ein Reporting und CDSS-System. AIDKlinik hat einen AMTS-Check nutzt hierfür auch die offiziellen Listen der Fachinfos, vgl. https://www.dosing-gmbh.de/produktloesungen/aidklinik-2/

Insbesondere händische Recherche der Informationen notwendig.
